### ISSUE TITLE
access to gps?

### ISSUE THREAD

**Issue by johnwillyn** [bwindels/exif-parser#10]
Does the parser provide access to the gps and camera parameter data?  I am looking through the code (nicely done!) and I am not sure how or if it is stored on the result.

Thanks in advance.

JohnL

**Comment by bwindels** [comment]
Yes, you can access the latitude and longitude, if present, through the `GPSLatitude` and `GPSLongitude` tags. See https://github.com/bwindels/exif-parser#getting-the-tags.
I can see how this is not super obvious, maybe including some examples would be a good idea.

**Comment by bwindels** [comment]
By camera parameter, I assume you mean the model of the camera. This is stored in the `Model` tag.
