### ISSUE TITLE
Wrong detection of Orientation tag ?

### ISSUE THREAD

**Issue by geonanorch** [bwindels/exif-parser#21]
While using [jimp](https://github.com/oliver-moran/jimp) I noticed that some pictures got wrongly rotated based on their EXIF value. Those orientation values are coming straight from `exif-parser`. I traced the call and for the attached picture `exif-parser` will return an orientation `6`, which seems wrong (compared to several other tools I used to check the image).

Note: I replaced jimp's version of the library with the latest master, same behavior.

![dsc02857_small](https://cloud.githubusercontent.com/assets/19654936/24556487/d296898e-1634-11e7-8975-8d7b9f5ecdbd.JPG)
(file also available [here](http://desirenet.ronan.io/dl.php?file=DSC02857_small.JPG)).

**Comment by geonanorch** [comment]
Just saw PR #20, which might be related to this.

**Comment by bwindels** [comment]
Can you check if this is fixed in version 0.1.10?

**Comment by geonanorch** [comment]
Just tested against master (so 0.1.11), indeed the issue is fixed. Closing this issue, thank you!
