### ISSUE TITLE
Broken Update?

### ISSUE THREAD

**Issue by bneigher** [bwindels/exif-parser#25]
I am getting an empty tags array after this update 2 days ago.  Was working on previous version... any ideas?

Can you also tag your releases so they are zipped?

**Comment by bpatrik** [comment]
Same here works fine with version 0.1.9

**Comment by bpatrik** [comment]
There was a missing '!' at parser.js:174. 
I made a PR to fix it.

**Comment by bwindels** [comment]
Thank you all for reporting this! This shows I need to run the tests automatically ... I've released 0.1.12 to fix this issue.
